### ISSUE TITLE
videos and tactile data are not synchronized.

### ISSUE THREAD

**Issue by priteshgohil** [bravebin/Visual-Tactile_Dataset#1]
Hi, 
I was trying to visualize your dataset and trying match video with tactile data. Since frame per second for the camera is 18 and for tactile sensor sampling rate is 16.7Hz, I can not compare directly.

Then I read your published paper and did a plot of the tactile graph for the same object "Scrub 150-866 top-5 tactile". But again no match.

One more issue I found is a value from tactile is the same for the pair of the tactile sensor in the same finger. Could you please verify the tactile sensor values are updated propertly in the files?

Thank you.

**Comment by wangtaofree** [comment]
Hi,
Very thanks for your attention.
For the first point, it's really a drawback of current dataset, the frequency of video and tactile data is different, you should do more work to compare them;
For the 2nd, I've just checked the data and it seems no problem, the data shown in paper use the logarithmic coordinates, that may be the reason;
For the 3rd, I didn't get the point, could you explain again?
Thanks.

**Comment by priteshgohil** [comment]
Hi,
Thank you for the dataset and your quick reply.

For the 1st point, I hope label.txt will help me to compare it between tactile and video. However, if you have any suggestions, It would be nice.

In 2nd point, thanks for pointing out the logarithmic scale. I did a plot, it is perfect now. But I'm not able to interpret or correlate the lable.txt with video or tactile data. How the time is encoded in label.txt ? how can I compare it with tactile.txt data? It would be great if you can give a pointer or hint here. These 3 timestamps can be seen in the attached file.

To Explain 3rd point, I plot the tactile graph which can be accessed here [Tactile.pdf](https://github.com/tsinghua-rll/Visual-Tactile_Dataset/files/3413354/Tactile.pdf)
. I hope that I plotted it correctly. In the plot, we can see that tactile data from position  0&3, 1&2, 4&7, 5&6 and so on are identical. I do not understand why do I get the identical data between the pair of tactile sensors. I checked multiple time if I'm plotting it correctly.

Thank you again.

**Comment by wangtaofree** [comment]
The time label means the frame in the force data, such as "Cheez/100_432/right/0/label.txt",     
6.900000000000000000e+01 start grasp
1.040000000000000000e+02 use current loop
1.540000000000000000e+02 stop on the top position
1.000000000000000000e+00 success
You can check the description in the related paper.

For the 3rd point, I've checked the origin data, there seems really have some problem, maybe there is some problem when saving the data.
I'll double check it and update the dataset if there have any questions. It may take longer time.
Before I update the data, I think the valid data is still useful.
Thank you very much!

**Comment by priteshgohil** [comment]
I was not thinking first three label as a frame count. Instead I was trying to assign time unit directly. 

But now it is clear thank you.

**Comment by priteshgohil** [comment]
For the first point could you suggest what more work need to be done to compare tactile and video data? Since comparing tactile data and video is very important and my approach doesn't look to be good.

My approach:
1. Getting time of 3 different loops from label.txt
2. looked into corresponding RGB video and tried to find start grasp time, current loop and stop position time manually. (by pausing the video and looking carefully) 
3. I observed three different objects and noticed that start grasp time is not unique. The difference between tactile and video start time is not same for the different objects. 
For example, 
     Scrub: In tactile, start grasp is 3.12 second, whereas for video it is roughly 5 second. 
     Latte (150-620 top-8): In tactile, start time - 3.17 sec, In video, start time - 8 sec. 
     Water (150-1045 right-1): tactile start time- 4.14 sec, In video, start time - 6.5 sec. 

Since start time is different in videos, checking every video with tactile data will be a hard task.

**Comment by wangtaofree** [comment]
Hello, 
Thanks for the detail feedback, I've checked with the tactile data and found there really have some "wrong data" you mentioned before. I'll update the wrong data part as soon, and I've checked that, the problem for these data is that the channel like 2/3/6/7 have been covered by the data in 0/1/4/5, but the force value is right.
"To Explain 3rd point, I plot the tactile graph which can be accessed here Tactile.pdf. I hope that I plotted it correctly. In the plot, we can see that tactile data from position 0&3, 1&2, 4&7, 5&6 and so on are identical. I do not understand why do I get the identical data between the pair of tactile sensors. I checked multiple time if I'm plotting it correctly."

For the synchronize solution, I also do the similar way as you do, I also found it's really hard task, I can only say that I'll pay more attention to this part in future possible dataset. So sorry about it.
For current dataset, I can provide a suggestion that, for every item with same grasp current, we use the same program parameter, the video and label record time should be same. Wish it can help you!

**Comment by wangtaofree** [comment]
I've modified the tactile data part right now. But, due to I didn't have git clone the dataset in my current PC, it may take long time for me to download the dataset. You can change the tactile part with the zip in attach, and I'll update the git as soon. Thanks.
[tactile_data.zip](https://github.com/tsinghua-rll/Visual-Tactile_Dataset/files/3537078/tactile_data.zip)

**Comment by wangtaofree** [comment]
Already updated the dataset.

**Comment by priteshgohil** [comment]
Thank you for the correct data. :)
